spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  profiles:
    active: dev